### ISSUE TITLE
Packaging when releasing on cargo

### ISSUE THREAD

**Issue by jbtrystram** [jmfiaschi/json_value_merge#1]
Hello, 

I am packaging this crate for fedora as i use it as a dependency for my project, and here are a couple things that can be improved for easier packaging and distribution on crates.io : 

- add the readme in the crate with `readme = "README.md"` in your Cargo.toml file.
- remove the bench folder and the dependencies when publishing to crates.io, as someone using this as a library doesn't need to get the bench code :) 

Thanks ! 
FYI : here is the spec file for the fedora RPM : https://gitlab.com/jbtrystram/rust-json_merge_values
I'll open a PR whith it when the package is approved in fedora : https://bugzilla.redhat.com/show_bug.cgi?id=1978682

**Comment by jmfiaschi** [comment]
Hello,

My feedbacks : 
* add the readme in the crate with readme = "README.md" in your Cargo.toml file. => already in the file [here](https://github.com/jmfiaschi/json_value_merge/blob/master/Cargo.toml#L11)
*  remove the bench folder and the dependencies when publishing to crates.io, as someone using this as a library doesn't need to get the bench code :) => You are right :) I will do it, thanks

**Comment by jmfiaschi** [comment]
For the readme, I forget to release the 0.1.2. Maybe your issue is due to that.

**Comment by jbtrystram** [comment]
> For the readme, I forget to release the 0.1.2. Maybe your issue is due to that.

It looks like the `readme` field was already in the CArgo fiel prior to 0.1.2 so I am not sure why it's not in the crate when downloading from crates.io... 
Thanks for doing the changes though :)

**Comment by jmfiaschi** [comment]
I think it's due because I just add it in the include part of the package in the Cargo.toml. I fix an issue for the packaging and deploy a new version

**Comment by jmfiaschi** [comment]
Now it's good :)
