### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by sonicrules1234** [jmfiaschi/json_value_merge#10]
I'm getting a memory leak after calling the merge function lots of times.

**Comment by jmfiaschi** [comment]
Hello, thank you to report the issue. Can you give me more information, like the type of data you try do merge ? Is the structure is deep ? do you have an example please ?

**Comment by sonicrules1234** [comment]
Here's an example:
`fn merge_together(&self, root: SonicObject, key_value_vec: Vec<(serde_json::Value, serde_json::Value)>) -> SonicObject {
    /// SonicObject is a container I made that I put Values in.  .value is a Value
    let mut rootval = root.value.clone();
    let mut keylist: Vec<String> = Vec::new();
    for (key, _value) in key_value_vec.clone() {
        keylist.push(serde_json::to_value(key).unwrap().to_string());
    }
    for x in 0..(keylist.len()) {
        rootval.merge_in(format!("/{}", keylist.clone()[..(x + 1)].join("/")).as_str(), key_value_vec[x].1.clone());
    }
    SonicObject::new(rootval)
}`
It does get deep at times.

**Comment by jmfiaschi** [comment]
what is the max len of the keylist in your example ?

**Comment by sonicrules1234** [comment]
The highest I've seen it go is 10.

**Comment by jmfiaschi** [comment]
can you try with this : 
json_value_merge = { git = "https://github.com/jmfiaschi/json_value_merge", branch = "beta" }

**Comment by jmfiaschi** [comment]
I think i found the issue. I not cover all key in the json pointer like ~0 ~1 that is interpreted and can create infinit loop in my code. Can you test ?

**Comment by jmfiaschi** [comment]
Without feedback or more details, I close the issue
