### ISSUE TITLE
Breaking change in minor version 1.2.0

### ISSUE THREAD

**Issue by ia0** [jmfiaschi/json_value_merge#18]
Hi,

#15 introduces a [breaking change](https://github.com/jmfiaschi/json_value_merge/pull/15/files#r1322711580) but is released under a minor bump only.

Is it possible to yank 1.2.0 and instead release 2.0.0?

Thanks!

**Comment by jmfiaschi** [comment]
Thanks for your feedback, you are right :)

**Comment by ia0** [comment]
Thanks for the quick fix!
